# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='song_sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackTitle', models.CharField(max_length=255)),
                ('trackPermalink_url', models.CharField(max_length=255)),
            ],
        ),
    ]
