# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0002_song_sc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='song_sc',
            new_name='songSc',
        ),
    ]
