# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0003_auto_20160728_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_sc',
            name='user',
        ),
        migrations.RenameField(
            model_name='songsc',
            old_name='trackPermalink_url',
            new_name='permalink_url',
        ),
        migrations.RenameField(
            model_name='songsc',
            old_name='trackTitle',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='profile_sc',
        ),
    ]
